version: '2'

services:
  postgres:
    image: postgres
    container_name: "jbloggerdb"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres

  fakesmtp:
    build: ./support/fakesmtp
    container_name: "fakesmtpserver"
    ports:
     - "2525:25"

  jblogger:
    build: .
    container_name: jblogger
    ports:
     - "9090:8080"
    depends_on:
      - postgres
      - fakesmtp
